### ISSUE TITLE
Package ManifestHiedra should be tagged

### ISSUE THREAD

**Issue by astares** [tinchodias/hiedra#2]
@tinchodias 

see bug    https://pharo.fogbugz.com/f/cases/22742
and simple fix directly for Pharo 7 image in 

https://github.com/pharo-project/pharo/pull/2051

same should be done in official repo of hiedra

**Comment by tinchodias** [comment]
This is old now since your change in Pharo repository is also here (from time to time I merge community contributions from that repo to this one).

**Comment by tinchodias** [comment]
Thanks @astares :)
