### ISSUE TITLE
Roassal3 renderer: fix funny loop

### ISSUE THREAD

**Issue by tinchodias** [tinchodias/hiedra#4]
Example:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/3044265/56842387-9eb11580-6862-11e9-9155-7c106644eda5.png">

They usually appear with this sentence: ```HiRS3FastTableExample example60RandomCommits```.

They do not appear anymore with changing 12 to 10 here:
~~~
HiRS3Renderer>>cellWidth
	^ 12
~~~

It looks like an issue of Roassal3, in fact. @akevalion.

**Comment by akevalion** [comment]
The reason about this is the corner radius in polygon with cornerRadius 0 this does not have any effect

**Comment by akevalion** [comment]
This error occurs with 

```Smalltalk
cp := {(144@180). (120@160). (96@140).}.

v := RSView new.
v addShape: (TSPolyline new
	cornerRadii: 5;
	controlPoints: cp).
v zoomToFit.
v open.
```
![image](https://user-images.githubusercontent.com/10532890/57414941-377f5380-71c8-11e9-85b9-37db1c9d9eb5.png)

**Comment by akevalion** [comment]
And fixed
![image](https://user-images.githubusercontent.com/10532890/57415418-161f6700-71ca-11e9-935e-d62193d8b24d.png)

![image](https://user-images.githubusercontent.com/10532890/57415483-61d21080-71ca-11e9-86ed-db1e7969110b.png)

Please review this on hiedra

**Comment by akevalion** [comment]
He have this issue
```Smalltalk
v := RSView new.
s := TSPolyline new
	cornerRadii: 5;
	controlPoints: {(84@8000). (60@8020). (36@8040).}.
v addShape: s.
v zoomToFit.
v open.
```
![image](https://user-images.githubusercontent.com/10532890/57957994-510d5300-78cc-11e9-94f4-2042d79fa27d.png)

**Comment by akevalion** [comment]
Fixed in the last version please review

**Comment by tinchodias** [comment]
Yes it looks fixed now. Let's close it. Thanks!
