### ISSUE TITLE
Error when loading in a fresh Pharo 7 image

### ISSUE THREAD

**Issue by bergel** [tinchodias/hiedra#7]
```Smalltalk
Metacello new repository: 'github://tinchodias/hiedra:roassal3/src';
baseline: 'Hiedra'; load.
```

![image](https://user-images.githubusercontent.com/393742/58995340-d7c59980-87c1-11e9-8635-e4e45eeaa431.png)

**Comment by tinchodias** [comment]
Thanks for the report. the (experimental) roassal3 branch only works in pharo 8. I would close.
